### ISSUE TITLE
expecting to see stock market news on this 

### ISSUE THREAD

**Issue by EsqerYasen** [joshwallerr/newsnotfound#18]
i can see a huge potencial on finance area .

**Comment by EsqerYasen** [comment]
nasdaq , yahu news , seekingalpha ...

**Comment by joshwallerr** [comment]
I've opened a new issue at #27 to address this in more detail.

I'm working on getting real-time finance feeds setup, including stock market news.

I'll close this issue for now. Please refer to #27 for tracking progress.
