### ISSUE TITLE
RSS feeds for reading

### ISSUE THREAD

**Issue by perler** [joshwallerr/newsnotfound#19]
..can we get RSS feeds for reading the news from the website?

**Comment by joshwallerr** [comment]
There actually is - if you add '/feed' to the end of any category page (e.g. https://newsnotfound.com/world), you can get the RSS feed URL.

Where would you expect to see this on the site?

Maybe if there was an RSS icon near the heading of each category page where the red circle is:

![image](https://user-images.githubusercontent.com/97132509/234072036-25e7c43c-5bb2-4d2c-8ef7-5b3e9983b644.png)

**Comment by joshwallerr** [comment]
This has now been added on all category pages:

![image](https://user-images.githubusercontent.com/97132509/234383029-5b252113-ee15-4b83-bbaf-b52690d3ef0b.png)
